server:
  port: 4000
chrome:
  path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  remote_debugging_port: 9021
log:
  syslog:
    filename: /Volumes/user/var/log/otter_hls_server/system
    pattern: -2006-01-02
    level: debug
