server:
  port: 4000
chrome:
  path:
    windows: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
    macos: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
  remote_debugging_port: 9021
log:
  syslog:
    filename: /Volumes/user/var/log/otter_hls_server/system
    pattern: -2006-01-02
    level: debug
